export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_AUTHOR_INFO = 'USER_AUTHOR_INFO';

export const COM_OPEN_AUTHMODAL = 'COM_OPEN_AUTHMODAL'
export const COM_CLOSE_AUTHMODAL = 'COM_CLOSE_AUTHMODAL'
export const COMMON_COLOR_MAP = 'COMMON_COLOR_MAP'
export const COM_SET_WINDOW_WIDTH = 'COM_GET_WINDOW_WIDTH'
